import { motion } from 'framer-motion'
import { ArrowRight, Cloud, Server } from 'lucide-react'
import Navigation from '../components/Navigation'
import { Button } from '../components/ui/Button'

const BOOK_A_CALL_URL = 'https://calendly.com/tudor-caloian/30min'

const AboutPage = () => {
  return (
    <div className="min-h-screen bg-white">
      <Navigation />

      {/* Hero */}
      <section className="pt-32 pb-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="max-w-4xl"
          >
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold text-[#1a1a1a] mb-6">
              About DashExecs
            </h1>
            <p className="text-xl md:text-2xl text-gray-600">
              We build custom tools that match your frameworks and workflows to track the value generated by AI across your organization.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Mission */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-gray-50">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="max-w-4xl"
          >
            <h2 className="text-3xl md:text-4xl font-bold text-[#1a1a1a] mb-6">
              Mission
            </h2>
            <p className="text-lg text-gray-600 mb-4">
              AI initiatives are transforming organizations, but measuring their true impact remains a challenge. 
              DashExecs bridges this gap by providing executives with clear, actionable insights into the ROI of every AI use case.
            </p>
            <p className="text-lg text-gray-600 mb-4">
              From ambition to actuals, we help leaders see where AI is creating value—and what to do next.
            </p>
            <p className="text-lg text-gray-600">
              We build a custom solution that matches your existing frameworks, workflows, and reporting requirements, 
              ensuring seamless integration with how your organization already operates.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Founder */}
      <section className="py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="max-w-4xl"
          >
            <h2 className="text-3xl md:text-4xl font-bold text-[#1a1a1a] mb-6">
              Founder
            </h2>
            <div className="mb-0">
              <h3 className="text-2xl font-bold text-[#1a1a1a] mb-4">
                Tudor Caloian
              </h3>
              <p className="text-lg text-gray-600 mb-4">
                While working at Orange, he helped implement a comprehensive AI value tracking system across 26 countries which resulted in tracking <span className="font-bold text-[#1a1a1a]">€300M in AI use case value in 2025</span>.
              </p>
              <p className="text-lg text-gray-600">
                His mission is to replicate this success for other organizations, bringing the same level of clarity, 
                accountability, and value realization to AI initiatives worldwide.
              </p>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Deployment Options */}
      <section className="py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <h2 className="text-3xl md:text-4xl font-bold text-[#1a1a1a] mb-12 text-center">
              Flexible Deployment
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="border border-gray-200 p-8">
                <Server className="w-12 h-12 text-[#1a1a1a] mb-4" />
                <h3 className="text-2xl font-bold text-[#1a1a1a] mb-4">On-Premise</h3>
                <ul className="space-y-3 text-gray-600">
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-1">✓</span>
                    Full control over your data
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-1">✓</span>
                    Deploy within your existing infrastructure
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-1">✓</span>
                    Meet strict compliance requirements
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-1">✓</span>
                    Integrate with internal systems
                  </li>
                </ul>
              </div>
              <div className="border border-gray-200 p-8">
                <Cloud className="w-12 h-12 text-[#1a1a1a] mb-4" />
                <h3 className="text-2xl font-bold text-[#1a1a1a] mb-4">Cloud</h3>
                <ul className="space-y-3 text-gray-600">
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-1">✓</span>
                    Quick setup and deployment
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-1">✓</span>
                    Automatic updates and maintenance
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-1">✓</span>
                    Scalable infrastructure
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-1">✓</span>
                    Enterprise-grade security
                  </li>
                </ul>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 bg-[#1a1a1a]">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
              Ready to track AI ROI?
            </h2>
            <p className="text-xl text-gray-400 mb-8">
              Let's discuss how DashExecs can be customized for your organization.
            </p>
            <a href={BOOK_A_CALL_URL} target="_blank" rel="noreferrer">
              <Button variant="secondary" size="lg" className="flex items-center gap-2 mx-auto">
                Book a Call
                <ArrowRight className="w-5 h-5" />
              </Button>
            </a>
          </motion.div>
        </div>
      </section>
    </div>
  )
}

export default AboutPage

